/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_7d799f19 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/teklpnqyqvpzmvurhjud/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// PostgREST corta CADA respuesta en 1000 filas (db-max-rows) y no avisa:
// responde 200 con la lista recortada. Un .limit(10000) del cliente tampoco
// lo sube, el tope es del servidor. Como el escaneo va por la PK (key) en
// orden ascendente y las keys llevan el epoch adentro (venta:VEN-<ms>-...),
// lo que se pierde en silencio son SIEMPRE los registros mas nuevos.
// Por eso toda lectura por prefijo se pagina con .range() hasta agotar el
// prefijo. El .order("key") no es cosmetico: sin un orden estable, las
// paginas de .range() pueden repetir o saltarse filas.
const PAGE_SIZE = 1000;

// Lee TODAS las filas de un prefijo (key + value crudos), paginando.
export const getRowsByPrefix = async (
  prefix: string,
): Promise<{ key: string; value: any }[]> => {
  const supabase = client()
  const rows: { key: string; value: any }[] = [];

  for (let desde = 0; ; desde += PAGE_SIZE) {
    const { data, error } = await supabase
      .from("kv_store_7d799f19")
      .select("key, value")
      .like("key", prefix + "%")
      .order("key", { ascending: true })
      .range(desde, desde + PAGE_SIZE - 1);

    if (error) {
      throw new Error(error.message);
    }
    if (!data || data.length === 0) {
      break;
    }

    rows.push(...data);

    // Pagina incompleta = ya no hay mas.
    if (data.length < PAGE_SIZE) {
      break;
    }
  }

  return rows;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7d799f19").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_7d799f19").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7d799f19").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7d799f19").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const valores: any[] = [];

  // Mismo tope de 1000 filas: si se piden mas de 1000 keys de un jalon,
  // la respuesta vuelve recortada. Se consulta por bloques.
  for (let i = 0; i < keys.length; i += PAGE_SIZE) {
    const bloque = keys.slice(i, i + PAGE_SIZE);
    const { data, error } = await supabase.from("kv_store_7d799f19").select("value").in("key", bloque);
    if (error) {
      throw new Error(error.message);
    }
    valores.push(...(data?.map((d) => d.value) ?? []));
  }

  return valores;
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7d799f19").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const rows = await getRowsByPrefix(prefix);
  // Incluir el 'key' como 'id' en cada objeto retornado si no existe
  return rows.map((d) => ({ id: d.key, ...d.value }));
};
